vich_uploader:
    db_driver: orm

    mappings:
       article_image:
            uri_prefix: /image/articles/imagePrincipale
            upload_destination: '%kernel.project_dir%/public/image/articles/imagePrincipale'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
       article_photo:
            uri_prefix: /image/articles/photo
            upload_destination: '%kernel.project_dir%/public/image/articles/photo'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
       article_photo2:
            uri_prefix: /image/articles/photo2
            upload_destination: '%kernel.project_dir%/public/image/articles/photo2'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
       article_photo3:
            uri_prefix: /image/articles/photo
            upload_destination: '%kernel.project_dir%/public/image/articles/photo3'
            namer: Vich\UploaderBundle\Naming\UniqidNamer